### ISSUE TITLE
Verbose logging should be opt-in, even for CI

### ISSUE THREAD

**Issue by ffMathy** [TriPSs/nx-extend#154]
Right now, the verbose logging is always enabled for CI. I don't think that should be the case. The `pulumi up` output is very verbose because of it.

**Comment by TriPSs** [comment]
I actually did that intentionally (for all packages) as I found it very annoying not to be able to see everything/reason of failing and than needed to restart the job with debug enabled.

We could probably improve this, any suggestions?

**Comment by ffMathy** [comment]
But then why not just have it react on an environment variable, and then set that environment variable globally in the CI?

**Comment by ffMathy** [comment]
The reason is that right now, a simple pulumi preview contains 1400 lines of logs. 3 of those lines show me what pulumi intends to change. The rest is just noise, if that makes sense.

**Comment by TriPSs** [comment]
Because I'm lazy 😂, instead of needing to update multiple CI's I just added it here.

I can understand this would be annoying for Pulumi, if you want you can create a different const that does not contain the ci check and use that one for Pulumi.

**Comment by ffMathy** [comment]
Well, it's your project I suppose, and it was always intended for your needs. I respect that.

What do you mean different const?

And can you mention why it is you need verbose logging? Is it because you often find something wrong that needs the verbosity?

**Comment by TriPSs** [comment]
When deploying my Cloud Functions (@nx-extend/gcp-functions), Cloud Run (@nx-extend/gcp-cloud-run), Vercel (@nx-extend/vercel), Firebase (@nx-extend/firebase-hosting) or updating my secrets (@nx-extend/gcp-secrets) or even when running my tests (@nx-extend/e2e-runner), it they fail I would rather directly see that caused it instead of me having to rerun with debug mode on, especially in the CI as you need to pay for minutes but not log size.

Examples:
- When running my e2e tests without debug mode the tests can fail, but did they fail because one of my API's was unable to start? I don't know, need to restart first.

- When deploying anything in the CI (It are big projects so these things take time) and one of the deploys fails I want to see why and not restart with debug mode, wait another 10 minutes for the same error and than resolve it.


Note that all of these things logs a little extra, not like pulumi 1400 lines 😅 

Regarding the const: 
```ts
export const USE_VERBOSE_LOGGING = isCI() || Boolean(process.env.NX_VERBOSE_LOGGING)
```

We add (Better name suggestions welcome)
```ts
export const USE_VERBOSE_LOGGING_MINIMAL = Boolean(process.env.NX_VERBOSE_LOGGING || process.env. ACTIONS_RUNNER_DEBUG)
```

**Comment by ffMathy** [comment]
But if you're in doubt of whether it's because one of your APIs didn't start etc, shouldn't those messages be logged with higher verbosity?

And what I meant was that setting an environment variable globally for all jobs in a GitHub action work flow is quite easy.

As for the const, I guess that would work. As long as it doesn't do it for Pulumi, because that's really bad apparently 😅

**Comment by TriPSs** [comment]
>As for the const, I guess that would work. As long as it doesn't do it for Pulumi, because that's really bad apparently 😅

I don't understand this one, could you elaborate a bit more? Making that constant will not work for Pulumi?

**Comment by ffMathy** [comment]
Ah yes that was indeed phrased weirdly. Yes, making a const would probably work for Pulumi. I think it's a good idea.

Unfortunately, I am a bit hung up on time right now. Is it possible for you to sneak this in?

**Comment by ffMathy** [comment]
Thanks!
